//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AccountResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.AccountResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account For.
        /// </summary>
        internal static string AccountForText {
            get {
                return ResourceManager.GetString("AccountForText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account info.
        /// </summary>
        internal static string AccountInfoLabel {
            get {
                return ResourceManager.GetString("AccountInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Information.
        /// </summary>
        internal static string AccountInformationLabel {
            get {
                return ResourceManager.GetString("AccountInformationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addess list.
        /// </summary>
        internal static string AddessListLabel {
            get {
                return ResourceManager.GetString("AddessListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new.
        /// </summary>
        internal static string AddNewAddress {
            get {
                return ResourceManager.GetString("AddNewAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new address.
        /// </summary>
        internal static string AddNewAddressText {
            get {
                return ResourceManager.GetString("AddNewAddressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string AddressLabel {
            get {
                return ResourceManager.GetString("AddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address list.
        /// </summary>
        internal static string AddressListLabel {
            get {
                return ResourceManager.GetString("AddressListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address List.
        /// </summary>
        internal static string AddressListText {
            get {
                return ResourceManager.GetString("AddressListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string AddressText {
            get {
                return ResourceManager.GetString("AddressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back  to home.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string ChangePasswordText {
            get {
                return ResourceManager.GetString("ChangePasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City / State.
        /// </summary>
        internal static string CityStateLabel {
            get {
                return ResourceManager.GetString("CityStateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment product buyed.
        /// </summary>
        internal static string CommentProductBuyedLabel {
            get {
                return ResourceManager.GetString("CommentProductBuyedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name.
        /// </summary>
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copper member.
        /// </summary>
        internal static string CopperMember {
            get {
                return ResourceManager.GetString("CopperMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CopperMemberIcon {
            get {
                return ResourceManager.GetString("CopperMemberIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string CountryLabel {
            get {
                return ResourceManager.GetString("CountryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} points in your account..
        /// </summary>
        internal static string CurrentPointFormat {
            get {
                return ResourceManager.GetString("CurrentPointFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From date.
        /// </summary>
        internal static string CustomerDateFromLabel {
            get {
                return ResourceManager.GetString("CustomerDateFromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update customer.
        /// </summary>
        internal static string CustomerEditTitle {
            get {
                return ResourceManager.GetString("CustomerEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string CustomerEmailLabel {
            get {
                return ResourceManager.GetString("CustomerEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email of Referrer.
        /// </summary>
        internal static string CustomerEmailReferrerLabel {
            get {
                return ResourceManager.GetString("CustomerEmailReferrerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string CustomerFirstNameLabel {
            get {
                return ResourceManager.GetString("CustomerFirstNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer information.
        /// </summary>
        internal static string CustomerInfo {
            get {
                return ResourceManager.GetString("CustomerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string CustomerLastNameLabel {
            get {
                return ResourceManager.GetString("CustomerLastNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login name.
        /// </summary>
        internal static string CustomerLoginNameLabel {
            get {
                return ResourceManager.GetString("CustomerLoginNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string CustomerNameLabel {
            get {
                return ResourceManager.GetString("CustomerNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order history.
        /// </summary>
        internal static string CustomerOrderHistoryLabel {
            get {
                return ResourceManager.GetString("CustomerOrderHistoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        internal static string CustomerPhoneLabel {
            get {
                return ResourceManager.GetString("CustomerPhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number of Referrer.
        /// </summary>
        internal static string CustomerPhoneReferrerLabel {
            get {
                return ResourceManager.GetString("CustomerPhoneReferrerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers List.
        /// </summary>
        internal static string CustomersListTitle {
            get {
                return ResourceManager.GetString("CustomersListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed money.
        /// </summary>
        internal static string CustomerTotalConfirmedMoneyLabel {
            get {
                return ResourceManager.GetString("CustomerTotalConfirmedMoneyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total money spent.
        /// </summary>
        internal static string CustomerTotalMoneyLabel {
            get {
                return ResourceManager.GetString("CustomerTotalMoneyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders bought.
        /// </summary>
        internal static string CustomerTotalOrdersBoughtLabel {
            get {
                return ResourceManager.GetString("CustomerTotalOrdersBoughtLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unconfirmed money.
        /// </summary>
        internal static string CustomerTotalUnconfirmedMoneyLabel {
            get {
                return ResourceManager.GetString("CustomerTotalUnconfirmedMoneyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User code.
        /// </summary>
        internal static string CustomerUserIDLabel {
            get {
                return ResourceManager.GetString("CustomerUserIDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        internal static string DailyLabel {
            get {
                return ResourceManager.GetString("DailyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string DefaultAddress {
            get {
                return ResourceManager.GetString("DefaultAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string DefaultLabel {
            get {
                return ResourceManager.GetString("DefaultLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string DefaultText {
            get {
                return ResourceManager.GetString("DefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        internal static string DistrictLabel {
            get {
                return ResourceManager.GetString("DistrictLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete.
        /// </summary>
        internal static string DoYouReallyWantToDeleteLabel {
            get {
                return ResourceManager.GetString("DoYouReallyWantToDeleteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditLabel {
            get {
                return ResourceManager.GetString("EditLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditText {
            get {
                return ResourceManager.GetString("EditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit address.
        /// </summary>
        internal static string EditUserAddressText {
            get {
                return ResourceManager.GetString("EditUserAddressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required!.
        /// </summary>
        internal static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fri.
        /// </summary>
        internal static string FridayLabel {
            get {
                return ResourceManager.GetString("FridayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        internal static string FullNameLabel {
            get {
                return ResourceManager.GetString("FullNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name is required!.
        /// </summary>
        internal static string FullNameRequired {
            get {
                return ResourceManager.GetString("FullNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string FullNameText {
            get {
                return ResourceManager.GetString("FullNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Information.
        /// </summary>
        internal static string GeneralInformationLabel {
            get {
                return ResourceManager.GetString("GeneralInformationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General information.
        /// </summary>
        internal static string GeneralInformationLabel1 {
            get {
                return ResourceManager.GetString("GeneralInformationLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General information.
        /// </summary>
        internal static string GeneralInformationText {
            get {
                return ResourceManager.GetString("GeneralInformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Gold member.
        /// </summary>
        internal static string GoldMember {
            get {
                return ResourceManager.GetString("GoldMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;i class=&quot;fa fa-trophy&quot; aria-hidden=&quot;true&quot;&gt;&lt;/i&gt;.
        /// </summary>
        internal static string GoldMemberIcon {
            get {
                return ResourceManager.GetString("GoldMemberIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included VAT.
        /// </summary>
        internal static string IncludeVAT {
            get {
                return ResourceManager.GetString("IncludeVAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info Account.
        /// </summary>
        internal static string InfoAcountText {
            get {
                return ResourceManager.GetString("InfoAcountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Member.
        /// </summary>
        internal static string Member {
            get {
                return ResourceManager.GetString("Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MemberIcon {
            get {
                return ResourceManager.GetString("MemberIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon.
        /// </summary>
        internal static string MondayLabel {
            get {
                return ResourceManager.GetString("MondayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        internal static string MonthlyLabel {
            get {
                return ResourceManager.GetString("MonthlyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My comment.
        /// </summary>
        internal static string MyCommentLabel {
            get {
                return ResourceManager.GetString("MyCommentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My information.
        /// </summary>
        internal static string MyInfoLabel {
            get {
                return ResourceManager.GetString("MyInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My information.
        /// </summary>
        internal static string MyInfoText {
            get {
                return ResourceManager.GetString("MyInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Orders.
        /// </summary>
        internal static string MyOrdersLabel {
            get {
                return ResourceManager.GetString("MyOrdersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order details.
        /// </summary>
        internal static string OrderDetailLabel {
            get {
                return ResourceManager.GetString("OrderDetailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order list.
        /// </summary>
        internal static string OrderListText {
            get {
                return ResourceManager.GetString("OrderListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order List.
        /// </summary>
        internal static string OrderListText1 {
            get {
                return ResourceManager.GetString("OrderListText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order is not existed !.
        /// </summary>
        internal static string OrderNotExist {
            get {
                return ResourceManager.GetString("OrderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Products.
        /// </summary>
        internal static string OrderScheduleAddProductsText {
            get {
                return ResourceManager.GetString("OrderScheduleAddProductsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        internal static string OrderScheduleAddressLabel {
            get {
                return ResourceManager.GetString("OrderScheduleAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After every.
        /// </summary>
        internal static string OrderScheduleAfterEvery2Label {
            get {
                return ResourceManager.GetString("OrderScheduleAfterEvery2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to after every.
        /// </summary>
        internal static string OrderScheduleAfterEveryLabel {
            get {
                return ResourceManager.GetString("OrderScheduleAfterEveryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Order.
        /// </summary>
        internal static string OrderScheduleConfirmationHeading {
            get {
                return ResourceManager.GetString("OrderScheduleConfirmationHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order schedule confirmation.
        /// </summary>
        internal static string OrderScheduleConfirmationLabel {
            get {
                return ResourceManager.GetString("OrderScheduleConfirmationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string OrderScheduleConfirmText {
            get {
                return ResourceManager.GetString("OrderScheduleConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        internal static string OrderScheduleCreatedDateText {
            get {
                return ResourceManager.GetString("OrderScheduleCreatedDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new order.
        /// </summary>
        internal static string OrderScheduleCreateNewLabel {
            get {
                return ResourceManager.GetString("OrderScheduleCreateNewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Order.
        /// </summary>
        internal static string OrderScheduleCreateNewText {
            get {
                return ResourceManager.GetString("OrderScheduleCreateNewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        internal static string OrderScheduleCreateText {
            get {
                return ResourceManager.GetString("OrderScheduleCreateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day(s).
        /// </summary>
        internal static string OrderScheduleDailyDaysLabel {
            get {
                return ResourceManager.GetString("OrderScheduleDailyDaysLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily:.
        /// </summary>
        internal static string OrderScheduleDailyLabel {
            get {
                return ResourceManager.GetString("OrderScheduleDailyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string OrderScheduleDeleteText {
            get {
                return ResourceManager.GetString("OrderScheduleDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date:.
        /// </summary>
        internal static string OrderScheduleEditEndDateLabel {
            get {
                return ResourceManager.GetString("OrderScheduleEditEndDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date:.
        /// </summary>
        internal static string OrderScheduleEditStartDateLabel {
            get {
                return ResourceManager.GetString("OrderScheduleEditStartDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string OrderScheduleEditText {
            get {
                return ResourceManager.GetString("OrderScheduleEditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour(s).
        /// </summary>
        internal static string OrderScheduleEmailAlarmHourLabel {
            get {
                return ResourceManager.GetString("OrderScheduleEmailAlarmHourLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send notification email before:.
        /// </summary>
        internal static string OrderScheduleEmailAlarmLabel {
            get {
                return ResourceManager.GetString("OrderScheduleEmailAlarmLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string OrderScheduleEnabledText {
            get {
                return ResourceManager.GetString("OrderScheduleEnabledText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable:.
        /// </summary>
        internal static string OrderScheduleEnableLabel {
            get {
                return ResourceManager.GetString("OrderScheduleEnableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Schedule.
        /// </summary>
        internal static string OrderScheduleHeading {
            get {
                return ResourceManager.GetString("OrderScheduleHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order schedule.
        /// </summary>
        internal static string OrderScheduleLabel {
            get {
                return ResourceManager.GetString("OrderScheduleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string OrderScheduleMonthlyDay2Label {
            get {
                return ResourceManager.GetString("OrderScheduleMonthlyDay2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        internal static string OrderScheduleMonthlyDayLabel {
            get {
                return ResourceManager.GetString("OrderScheduleMonthlyDayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly:.
        /// </summary>
        internal static string OrderScheduleMonthlyLabel {
            get {
                return ResourceManager.GetString("OrderScheduleMonthlyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month(s).
        /// </summary>
        internal static string OrderScheduleMonthlyMonthsLabel {
            get {
                return ResourceManager.GetString("OrderScheduleMonthlyMonthsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Name:.
        /// </summary>
        internal static string OrderScheduleNameLabel {
            get {
                return ResourceManager.GetString("OrderScheduleNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Name.
        /// </summary>
        internal static string OrderScheduleNameText {
            get {
                return ResourceManager.GetString("OrderScheduleNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occur:.
        /// </summary>
        internal static string OrderScheduleOccurLabel {
            get {
                return ResourceManager.GetString("OrderScheduleOccurLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method:.
        /// </summary>
        internal static string OrderSchedulePaymentMethodLabel {
            get {
                return ResourceManager.GetString("OrderSchedulePaymentMethodLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product List:.
        /// </summary>
        internal static string OrderScheduleProductListLabel {
            get {
                return ResourceManager.GetString("OrderScheduleProductListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string OrderScheduleProductsText {
            get {
                return ResourceManager.GetString("OrderScheduleProductsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        internal static string OrderScheduleScheduleText {
            get {
                return ResourceManager.GetString("OrderScheduleScheduleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Search.
        /// </summary>
        internal static string OrderScheduleSearchText {
            get {
                return ResourceManager.GetString("OrderScheduleSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping method:.
        /// </summary>
        internal static string OrderScheduleShippingMethodLabel {
            get {
                return ResourceManager.GetString("OrderScheduleShippingMethodLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        internal static string OrderScheduleSubtotalText {
            get {
                return ResourceManager.GetString("OrderScheduleSubtotalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string OrderScheduleUpdateText {
            get {
                return ResourceManager.GetString("OrderScheduleUpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly:.
        /// </summary>
        internal static string OrderScheduleWeeklyLabel {
            get {
                return ResourceManager.GetString("OrderScheduleWeeklyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to week(s).
        /// </summary>
        internal static string OrderScheduleWeeklyWeeksLabel {
            get {
                return ResourceManager.GetString("OrderScheduleWeeklyWeeksLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have &lt;strong&gt;{0}&lt;/strong&gt; bonus points pending.
        /// </summary>
        internal static string PendingPointFormat {
            get {
                return ResourceManager.GetString("PendingPointFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string PhoneLabel {
            get {
                return ResourceManager.GetString("PhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone not valid.
        /// </summary>
        internal static string PhoneNotValidLabel {
            get {
                return ResourceManager.GetString("PhoneNotValidLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        internal static string PhoneNumberLabel {
            get {
                return ResourceManager.GetString("PhoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is required!.
        /// </summary>
        internal static string PhoneNumberRequired {
            get {
                return ResourceManager.GetString("PhoneNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string PhoneText {
            get {
                return ResourceManager.GetString("PhoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your address .
        /// </summary>
        internal static string PleaseChooseAddressLabel {
            get {
                return ResourceManager.GetString("PleaseChooseAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose countryLabel.
        /// </summary>
        internal static string PleaseChooseCountryLabel {
            get {
                return ResourceManager.GetString("PleaseChooseCountryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose district.
        /// </summary>
        internal static string PleaseChooseDistrictLabel {
            get {
                return ResourceManager.GetString("PleaseChooseDistrictLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose province.
        /// </summary>
        internal static string PleaseChooseProvinceLabel {
            get {
                return ResourceManager.GetString("PleaseChooseProvinceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your city / state.
        /// </summary>
        internal static string PleaseEnterYourCityStateLabel {
            get {
                return ResourceManager.GetString("PleaseEnterYourCityStateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your name.
        /// </summary>
        internal static string PleaseEnterYourNameLabel {
            get {
                return ResourceManager.GetString("PleaseEnterYourNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your phone.
        /// </summary>
        internal static string PleaseEnterYourPhoneLabel {
            get {
                return ResourceManager.GetString("PleaseEnterYourPhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your post code / zip.
        /// </summary>
        internal static string PleaseEnterYourPostCodeLabel {
            get {
                return ResourceManager.GetString("PleaseEnterYourPostCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        internal static string Point {
            get {
                return ResourceManager.GetString("Point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        internal static string PointAcceptedStatus {
            get {
                return ResourceManager.GetString("PointAcceptedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string PointCancelStatus {
            get {
                return ResourceManager.GetString("PointCancelStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string PointContent {
            get {
                return ResourceManager.GetString("PointContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have &lt;strong&gt;{0}&lt;/strong&gt; bonus points.
        /// </summary>
        internal static string PointFomat {
            get {
                return ResourceManager.GetString("PointFomat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History of reward points.
        /// </summary>
        internal static string PointHistoryTitle {
            get {
                return ResourceManager.GetString("PointHistoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string PointPendingStatus {
            get {
                return ResourceManager.GetString("PointPendingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string PointStatus {
            get {
                return ResourceManager.GetString("PointStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string PointTime {
            get {
                return ResourceManager.GetString("PointTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostCode / Zip.
        /// </summary>
        internal static string PostCodeLabel {
            get {
                return ResourceManager.GetString("PostCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string ProductNameLabel {
            get {
                return ResourceManager.GetString("ProductNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product viewed.
        /// </summary>
        internal static string ProductViewedLabel {
            get {
                return ResourceManager.GetString("ProductViewedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        internal static string ProvinceLabel {
            get {
                return ResourceManager.GetString("ProvinceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get bonus points from orders.
        /// </summary>
        internal static string ReceivedFrom {
            get {
                return ResourceManager.GetString("ReceivedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent orders.
        /// </summary>
        internal static string RecentOrdersLabel {
            get {
                return ResourceManager.GetString("RecentOrdersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string RegisterDayLabel {
            get {
                return ResourceManager.GetString("RegisterDayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string RegisterMonthLabel {
            get {
                return ResourceManager.GetString("RegisterMonthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your registration.
        /// </summary>
        internal static string RegisterThanks {
            get {
                return ResourceManager.GetString("RegisterThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string RegisterYearLabel {
            get {
                return ResourceManager.GetString("RegisterYearLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request note.
        /// </summary>
        internal static string RequestNoteLabel {
            get {
                return ResourceManager.GetString("RequestNoteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request note is required!.
        /// </summary>
        internal static string RequestNoteRequired {
            get {
                return ResourceManager.GetString("RequestNoteRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request return order.
        /// </summary>
        internal static string RequestReturnOrderLabel {
            get {
                return ResourceManager.GetString("RequestReturnOrderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sat.
        /// </summary>
        internal static string SaturdayLabel {
            get {
                return ResourceManager.GetString("SaturdayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Silver member.
        /// </summary>
        internal static string SilverMember {
            get {
                return ResourceManager.GetString("SilverMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;i class=&quot;fa fa-trophy&quot; aria-hidden=&quot;true&quot;&gt;&lt;/i&gt;.
        /// </summary>
        internal static string SilverMemberIcon {
            get {
                return ResourceManager.GetString("SilverMemberIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit request.
        /// </summary>
        internal static string SubmitRequestButton {
            get {
                return ResourceManager.GetString("SubmitRequestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun.
        /// </summary>
        internal static string SundayLabel {
            get {
                return ResourceManager.GetString("SundayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu.
        /// </summary>
        internal static string ThursdayLabel {
            get {
                return ResourceManager.GetString("ThursdayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total points :.
        /// </summary>
        internal static string TotalPointUserHave {
            get {
                return ResourceManager.GetString("TotalPointUserHave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tue.
        /// </summary>
        internal static string TuesdayLabel {
            get {
                return ResourceManager.GetString("TuesdayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string UpdateButton {
            get {
                return ResourceManager.GetString("UpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this address as the default.
        /// </summary>
        internal static string UpdateDefaultAddress {
            get {
                return ResourceManager.GetString("UpdateDefaultAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The points required for {0} rank : {1}.
        /// </summary>
        internal static string UserMemberNextRankFormat {
            get {
                return ResourceManager.GetString("UserMemberNextRankFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your rank membership: {0} .
        /// </summary>
        internal static string UserMemberRankFormat {
            get {
                return ResourceManager.GetString("UserMemberRankFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User point history.
        /// </summary>
        internal static string UserPointHistoryLabel {
            get {
                return ResourceManager.GetString("UserPointHistoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User point histories.
        /// </summary>
        internal static string UserPointHistoryTitle {
            get {
                return ResourceManager.GetString("UserPointHistoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string UserProfileHomeLabel {
            get {
                return ResourceManager.GetString("UserProfileHomeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Notification.
        /// </summary>
        internal static string UserProfileMyNotificationLabel {
            get {
                return ResourceManager.GetString("UserProfileMyNotificationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Reviews.
        /// </summary>
        internal static string UserProfileMyReviewsLabel {
            get {
                return ResourceManager.GetString("UserProfileMyReviewsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product viewed.
        /// </summary>
        internal static string UserProfileProductViewedLabel {
            get {
                return ResourceManager.GetString("UserProfileProductViewedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Return.
        /// </summary>
        internal static string UserProfileRequestReturnOrderLabel {
            get {
                return ResourceManager.GetString("UserProfileRequestReturnOrderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews Products Purchased .
        /// </summary>
        internal static string UserProfileReviewsProductsPurchasedLabel {
            get {
                return ResourceManager.GetString("UserProfileReviewsProductsPurchasedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use This Addess Is Default.
        /// </summary>
        internal static string UseThisAddessIsDefault {
            get {
                return ResourceManager.GetString("UseThisAddessIsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this address is default.
        /// </summary>
        internal static string UseThisAddressToDefaultLabel {
            get {
                return ResourceManager.GetString("UseThisAddressToDefaultLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all.
        /// </summary>
        internal static string ViewAllLabel {
            get {
                return ResourceManager.GetString("ViewAllLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all.
        /// </summary>
        internal static string ViewAllText {
            get {
                return ResourceManager.GetString("ViewAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ward.
        /// </summary>
        internal static string WardLabel {
            get {
                return ResourceManager.GetString("WardLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wed.
        /// </summary>
        internal static string WednesdayLabel {
            get {
                return ResourceManager.GetString("WednesdayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        internal static string WeeklyLabel {
            get {
                return ResourceManager.GetString("WeeklyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome: {FirstName} {LastName}.
        /// </summary>
        internal static string WelcomeMessageFormat {
            get {
                return ResourceManager.GetString("WelcomeMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome: {FirstName} {LastName}.
        /// </summary>
        internal static string WelcomeMessageFormat1 {
            get {
                return ResourceManager.GetString("WelcomeMessageFormat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wish list.
        /// </summary>
        internal static string WishListText {
            get {
                return ResourceManager.GetString("WishListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wish List.
        /// </summary>
        internal static string WishListText1 {
            get {
                return ResourceManager.GetString("WishListText1", resourceCulture);
            }
        }
    }
}
