//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StoreResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StoreResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.StoreResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All stores.
        /// </summary>
        internal static string AllStoreDropdown {
            get {
                return ResourceManager.GetString("AllStoreDropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Endpoint.
        /// </summary>
        internal static string APIEndpointLabel {
            get {
                return ResourceManager.GetString("APIEndpointLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import inventories.
        /// </summary>
        internal static string ImportInventoryListTitle {
            get {
                return ResourceManager.GetString("ImportInventoryListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string InventoryAllText {
            get {
                return ResourceManager.GetString("InventoryAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Code.
        /// </summary>
        internal static string InventoryAPIProductIDLabel {
            get {
                return ResourceManager.GetString("InventoryAPIProductIDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string InventoryDisplayLabel {
            get {
                return ResourceManager.GetString("InventoryDisplayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit inventory.
        /// </summary>
        internal static string InventoryEditTitle {
            get {
                return ResourceManager.GetString("InventoryEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price from.
        /// </summary>
        internal static string InventoryFromPriceLabel {
            get {
                return ResourceManager.GetString("InventoryFromPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity from.
        /// </summary>
        internal static string InventoryFromQuantityLabel {
            get {
                return ResourceManager.GetString("InventoryFromQuantityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inputted products.
        /// </summary>
        internal static string InventoryInputtedText {
            get {
                return ResourceManager.GetString("InventoryInputtedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory management.
        /// </summary>
        internal static string InventoryListTitle {
            get {
                return ResourceManager.GetString("InventoryListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-inputted products.
        /// </summary>
        internal static string InventoryNonInputtedText {
            get {
                return ResourceManager.GetString("InventoryNonInputtedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a store.
        /// </summary>
        internal static string InventoryNoStoreMessage {
            get {
                return ResourceManager.GetString("InventoryNoStoreMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string InventoryPriceLabel {
            get {
                return ResourceManager.GetString("InventoryPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product code.
        /// </summary>
        internal static string InventoryProductCodeLabel {
            get {
                return ResourceManager.GetString("InventoryProductCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name.
        /// </summary>
        internal static string InventoryProductNameLabel {
            get {
                return ResourceManager.GetString("InventoryProductNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string InventoryQuantityLabel {
            get {
                return ResourceManager.GetString("InventoryQuantityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose status.
        /// </summary>
        internal static string InventoryStatusDropdown {
            get {
                return ResourceManager.GetString("InventoryStatusDropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string InventoryStatusLabel {
            get {
                return ResourceManager.GetString("InventoryStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In stock.
        /// </summary>
        internal static string InventoryStockDropdown {
            get {
                return ResourceManager.GetString("InventoryStockDropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of stock.
        /// </summary>
        internal static string InventoryStockoutDropdown {
            get {
                return ResourceManager.GetString("InventoryStockoutDropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose store.
        /// </summary>
        internal static string InventoryStoreDropdown {
            get {
                return ResourceManager.GetString("InventoryStoreDropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        internal static string InventoryStoreLabel {
            get {
                return ResourceManager.GetString("InventoryStoreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        internal static string InventoryStoreNameLabel {
            get {
                return ResourceManager.GetString("InventoryStoreNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        internal static string InventoryToLabel {
            get {
                return ResourceManager.GetString("InventoryToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers only.
        /// </summary>
        internal static string NumbersOnlyMessage {
            get {
                return ResourceManager.GetString("NumbersOnlyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        internal static string OrderStoreLabel {
            get {
                return ResourceManager.GetString("OrderStoreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string StoreAddressLabel {
            get {
                return ResourceManager.GetString("StoreAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store admins.
        /// </summary>
        internal static string StoreAdminLabel {
            get {
                return ResourceManager.GetString("StoreAdminLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District code.
        /// </summary>
        internal static string StoreAPIDistrictCodeLabel {
            get {
                return ResourceManager.GetString("StoreAPIDistrictCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        internal static string StoreChooseDropdown {
            get {
                return ResourceManager.GetString("StoreChooseDropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store code.
        /// </summary>
        internal static string StoreCodeLabel {
            get {
                return ResourceManager.GetString("StoreCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact person.
        /// </summary>
        internal static string StoreContactLabel {
            get {
                return ResourceManager.GetString("StoreContactLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string StoreDefaultLabel {
            get {
                return ResourceManager.GetString("StoreDefaultLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this attribute? It will be completely removed..
        /// </summary>
        internal static string StoreDeleteConfirmMessage {
            get {
                return ResourceManager.GetString("StoreDeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string StoreDescriptionLabel {
            get {
                return ResourceManager.GetString("StoreDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose district.
        /// </summary>
        internal static string StoreDistrictDropdown {
            get {
                return ResourceManager.GetString("StoreDistrictDropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        internal static string StoreDistrictLabel {
            get {
                return ResourceManager.GetString("StoreDistrictLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string StoreEditLink {
            get {
                return ResourceManager.GetString("StoreEditLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Store.
        /// </summary>
        internal static string StoreEditTitle {
            get {
                return ResourceManager.GetString("StoreEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string StoreEmailLabel {
            get {
                return ResourceManager.GetString("StoreEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax number.
        /// </summary>
        internal static string StoreFaxLabel {
            get {
                return ResourceManager.GetString("StoreFaxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store List.
        /// </summary>
        internal static string StoreListTitle {
            get {
                return ResourceManager.GetString("StoreListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managing areas.
        /// </summary>
        internal static string StoreManagingAreaLabel {
            get {
                return ResourceManager.GetString("StoreManagingAreaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string StoreNameLabel {
            get {
                return ResourceManager.GetString("StoreNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find suitable store. Please choose another store..
        /// </summary>
        internal static string StoreNotFoundInValid {
            get {
                return ResourceManager.GetString("StoreNotFoundInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option.
        /// </summary>
        internal static string StoreOptionLabel {
            get {
                return ResourceManager.GetString("StoreOptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take online order.
        /// </summary>
        internal static string StoreOptionOrderOnlineLabel {
            get {
                return ResourceManager.GetString("StoreOptionOrderOnlineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        internal static string StorePhoneLabel {
            get {
                return ResourceManager.GetString("StorePhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string StorePriorityLabel {
            get {
                return ResourceManager.GetString("StorePriorityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose province.
        /// </summary>
        internal static string StoreProvinceDropdown {
            get {
                return ResourceManager.GetString("StoreProvinceDropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        internal static string StoreProvinceLabel {
            get {
                return ResourceManager.GetString("StoreProvinceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show publicly.
        /// </summary>
        internal static string StorePublicLabel {
            get {
                return ResourceManager.GetString("StorePublicLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select store.
        /// </summary>
        internal static string StoreSelectLabel {
            get {
                return ResourceManager.GetString("StoreSelectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take online order.
        /// </summary>
        internal static string StoreTakeOnlineOrderLabel {
            get {
                return ResourceManager.GetString("StoreTakeOnlineOrderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update store priority.
        /// </summary>
        internal static string UpdateStorePriorityTitle {
            get {
                return ResourceManager.GetString("UpdateStorePriorityTitle", resourceCulture);
            }
        }
    }
}
