//------------------------------------------------------------------------------
// <auto-generated>
//     This productCode was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the productCode is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanhCam.Web.ProductUI {
    
    
    public partial class ProductSortBySetting {
        
        /// <summary>
        /// ddSortBy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to productCode-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddSortBy;
    }
}
